services:
  docker-manager:
    image: ghcr.io/codenotiz/docker-manager:latest
    container_name: docker-manager
    restart: unless-stopped
    
    # Zugriff auf den Docker-Daemon des Hosts
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - docker-manager-data:/app/data
      - docker-manager-stacks:/app/stacks_data
    # Falls dein Manager ein Web-Interface hat (hier Port 3000)
    ports:
      - "3000:3000"

    # Optionale Umgebungsvariablen
    environment:
      - NODE_ENV=production
      # - JWT_SECRET=your_super_secret_jwt_key_here
      # - LOG_LEVEL=INFO   # DEBUG | INFO | WARN | ERROR | SILENT (default: INFO)

volumes:
  docker-manager-data:
  docker-manager-stacks: